/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XmarksRouteImport } from './routes/xmarks'
import { Route as TickerRouteImport } from './routes/ticker'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SeeklyRouteImport } from './routes/seekly'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HelperRouteImport } from './routes/helper'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CleanseekXRouteImport } from './routes/cleanseek-x'
import { Route as CleanseekRouteImport } from './routes/cleanseek'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsIndexRouteImport } from './routes/labs/index'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as LabsXBattleRouteImport } from './routes/labs/x-battle'
import { Route as LabsPostRoomRouteImport } from './routes/labs/post-room'
import { Route as LabsMatrixRouteImport } from './routes/labs/matrix'
import { Route as LabsAntiEchoRouteImport } from './routes/labs/anti-echo'
import { Route as IndustriesVerticalRouteImport } from './routes/industries/$vertical'
import { Route as CleanseekXRabbitholexRouteImport } from './routes/cleanseek-x/rabbitholex'
import { Route as CleanseekXHistoryRouteImport } from './routes/cleanseek-x/history'
import { Route as CleanseekXDesktopRouteImport } from './routes/cleanseek-x/desktop'
import { Route as ApiUnusualWhalesRouteImport } from './routes/api/unusual-whales'
import { Route as ApiSupplementaryRouteImport } from './routes/api/supplementary'
import { Route as ApiSecondOpinionRouteImport } from './routes/api/second-opinion'
import { Route as ApiPulseVoicesRouteImport } from './routes/api/pulse-voices'
import { Route as ApiPulseRunsRouteImport } from './routes/api/pulse-runs'
import { Route as ApiXIntelXBattleRouteImport } from './routes/api/x-intel/x-battle'
import { Route as ApiXIntelPostRoomRouteImport } from './routes/api/x-intel/post-room'
import { Route as ApiXIntelAntiEchoRouteImport } from './routes/api/x-intel/anti-echo'

const XmarksRoute = XmarksRouteImport.update({
  id: '/xmarks',
  path: '/xmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerRoute = TickerRouteImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SeeklyRoute = SeeklyRouteImport.update({
  id: '/seekly',
  path: '/seekly',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperRoute = HelperRouteImport.update({
  id: '/helper',
  path: '/helper',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanseekXRoute = CleanseekXRouteImport.update({
  id: '/cleanseek-x',
  path: '/cleanseek-x',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanseekRoute = CleanseekRouteImport.update({
  id: '/cleanseek',
  path: '/cleanseek',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsXBattleRoute = LabsXBattleRouteImport.update({
  id: '/labs/x-battle',
  path: '/labs/x-battle',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsPostRoomRoute = LabsPostRoomRouteImport.update({
  id: '/labs/post-room',
  path: '/labs/post-room',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsMatrixRoute = LabsMatrixRouteImport.update({
  id: '/labs/matrix',
  path: '/labs/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsAntiEchoRoute = LabsAntiEchoRouteImport.update({
  id: '/labs/anti-echo',
  path: '/labs/anti-echo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesVerticalRoute = IndustriesVerticalRouteImport.update({
  id: '/industries/$vertical',
  path: '/industries/$vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanseekXRabbitholexRoute = CleanseekXRabbitholexRouteImport.update({
  id: '/rabbitholex',
  path: '/rabbitholex',
  getParentRoute: () => CleanseekXRoute,
} as any)
const CleanseekXHistoryRoute = CleanseekXHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CleanseekXRoute,
} as any)
const CleanseekXDesktopRoute = CleanseekXDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => CleanseekXRoute,
} as any)
const ApiUnusualWhalesRoute = ApiUnusualWhalesRouteImport.update({
  id: '/api/unusual-whales',
  path: '/api/unusual-whales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupplementaryRoute = ApiSupplementaryRouteImport.update({
  id: '/api/supplementary',
  path: '/api/supplementary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecondOpinionRoute = ApiSecondOpinionRouteImport.update({
  id: '/api/second-opinion',
  path: '/api/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseVoicesRoute = ApiPulseVoicesRouteImport.update({
  id: '/api/pulse-voices',
  path: '/api/pulse-voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPulseRunsRoute = ApiPulseRunsRouteImport.update({
  id: '/api/pulse-runs',
  path: '/api/pulse-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXIntelXBattleRoute = ApiXIntelXBattleRouteImport.update({
  id: '/api/x-intel/x-battle',
  path: '/api/x-intel/x-battle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXIntelPostRoomRoute = ApiXIntelPostRoomRouteImport.update({
  id: '/api/x-intel/post-room',
  path: '/api/x-intel/post-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXIntelAntiEchoRoute = ApiXIntelAntiEchoRouteImport.update({
  id: '/api/x-intel/anti-echo',
  path: '/api/x-intel/anti-echo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/cleanseek': typeof CleanseekRoute
  '/cleanseek-x': typeof CleanseekXRouteWithChildren
  '/faq': typeof FaqRoute
  '/helper': typeof HelperRoute
  '/pricing': typeof PricingRoute
  '/pulse': typeof PulseRoute
  '/seekly': typeof SeeklyRoute
  '/signin': typeof SigninRoute
  '/success': typeof SuccessRoute
  '/ticker': typeof TickerRoute
  '/xmarks': typeof XmarksRoute
  '/api/pulse-runs': typeof ApiPulseRunsRoute
  '/api/pulse-voices': typeof ApiPulseVoicesRoute
  '/api/second-opinion': typeof ApiSecondOpinionRoute
  '/api/supplementary': typeof ApiSupplementaryRoute
  '/api/unusual-whales': typeof ApiUnusualWhalesRoute
  '/cleanseek-x/desktop': typeof CleanseekXDesktopRoute
  '/cleanseek-x/history': typeof CleanseekXHistoryRoute
  '/cleanseek-x/rabbitholex': typeof CleanseekXRabbitholexRoute
  '/industries/$vertical': typeof IndustriesVerticalRoute
  '/labs/anti-echo': typeof LabsAntiEchoRoute
  '/labs/matrix': typeof LabsMatrixRoute
  '/labs/post-room': typeof LabsPostRoomRoute
  '/labs/x-battle': typeof LabsXBattleRoute
  '/industries/': typeof IndustriesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/api/x-intel/anti-echo': typeof ApiXIntelAntiEchoRoute
  '/api/x-intel/post-room': typeof ApiXIntelPostRoomRoute
  '/api/x-intel/x-battle': typeof ApiXIntelXBattleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/cleanseek': typeof CleanseekRoute
  '/cleanseek-x': typeof CleanseekXRouteWithChildren
  '/faq': typeof FaqRoute
  '/helper': typeof HelperRoute
  '/pricing': typeof PricingRoute
  '/pulse': typeof PulseRoute
  '/seekly': typeof SeeklyRoute
  '/signin': typeof SigninRoute
  '/success': typeof SuccessRoute
  '/ticker': typeof TickerRoute
  '/xmarks': typeof XmarksRoute
  '/api/pulse-runs': typeof ApiPulseRunsRoute
  '/api/pulse-voices': typeof ApiPulseVoicesRoute
  '/api/second-opinion': typeof ApiSecondOpinionRoute
  '/api/supplementary': typeof ApiSupplementaryRoute
  '/api/unusual-whales': typeof ApiUnusualWhalesRoute
  '/cleanseek-x/desktop': typeof CleanseekXDesktopRoute
  '/cleanseek-x/history': typeof CleanseekXHistoryRoute
  '/cleanseek-x/rabbitholex': typeof CleanseekXRabbitholexRoute
  '/industries/$vertical': typeof IndustriesVerticalRoute
  '/labs/anti-echo': typeof LabsAntiEchoRoute
  '/labs/matrix': typeof LabsMatrixRoute
  '/labs/post-room': typeof LabsPostRoomRoute
  '/labs/x-battle': typeof LabsXBattleRoute
  '/industries': typeof IndustriesIndexRoute
  '/labs': typeof LabsIndexRoute
  '/api/x-intel/anti-echo': typeof ApiXIntelAntiEchoRoute
  '/api/x-intel/post-room': typeof ApiXIntelPostRoomRoute
  '/api/x-intel/x-battle': typeof ApiXIntelXBattleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/cleanseek': typeof CleanseekRoute
  '/cleanseek-x': typeof CleanseekXRouteWithChildren
  '/faq': typeof FaqRoute
  '/helper': typeof HelperRoute
  '/pricing': typeof PricingRoute
  '/pulse': typeof PulseRoute
  '/seekly': typeof SeeklyRoute
  '/signin': typeof SigninRoute
  '/success': typeof SuccessRoute
  '/ticker': typeof TickerRoute
  '/xmarks': typeof XmarksRoute
  '/api/pulse-runs': typeof ApiPulseRunsRoute
  '/api/pulse-voices': typeof ApiPulseVoicesRoute
  '/api/second-opinion': typeof ApiSecondOpinionRoute
  '/api/supplementary': typeof ApiSupplementaryRoute
  '/api/unusual-whales': typeof ApiUnusualWhalesRoute
  '/cleanseek-x/desktop': typeof CleanseekXDesktopRoute
  '/cleanseek-x/history': typeof CleanseekXHistoryRoute
  '/cleanseek-x/rabbitholex': typeof CleanseekXRabbitholexRoute
  '/industries/$vertical': typeof IndustriesVerticalRoute
  '/labs/anti-echo': typeof LabsAntiEchoRoute
  '/labs/matrix': typeof LabsMatrixRoute
  '/labs/post-room': typeof LabsPostRoomRoute
  '/labs/x-battle': typeof LabsXBattleRoute
  '/industries/': typeof IndustriesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/api/x-intel/anti-echo': typeof ApiXIntelAntiEchoRoute
  '/api/x-intel/post-room': typeof ApiXIntelPostRoomRoute
  '/api/x-intel/x-battle': typeof ApiXIntelXBattleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/checkout'
    | '/cleanseek'
    | '/cleanseek-x'
    | '/faq'
    | '/helper'
    | '/pricing'
    | '/pulse'
    | '/seekly'
    | '/signin'
    | '/success'
    | '/ticker'
    | '/xmarks'
    | '/api/pulse-runs'
    | '/api/pulse-voices'
    | '/api/second-opinion'
    | '/api/supplementary'
    | '/api/unusual-whales'
    | '/cleanseek-x/desktop'
    | '/cleanseek-x/history'
    | '/cleanseek-x/rabbitholex'
    | '/industries/$vertical'
    | '/labs/anti-echo'
    | '/labs/matrix'
    | '/labs/post-room'
    | '/labs/x-battle'
    | '/industries/'
    | '/labs/'
    | '/api/x-intel/anti-echo'
    | '/api/x-intel/post-room'
    | '/api/x-intel/x-battle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/checkout'
    | '/cleanseek'
    | '/cleanseek-x'
    | '/faq'
    | '/helper'
    | '/pricing'
    | '/pulse'
    | '/seekly'
    | '/signin'
    | '/success'
    | '/ticker'
    | '/xmarks'
    | '/api/pulse-runs'
    | '/api/pulse-voices'
    | '/api/second-opinion'
    | '/api/supplementary'
    | '/api/unusual-whales'
    | '/cleanseek-x/desktop'
    | '/cleanseek-x/history'
    | '/cleanseek-x/rabbitholex'
    | '/industries/$vertical'
    | '/labs/anti-echo'
    | '/labs/matrix'
    | '/labs/post-room'
    | '/labs/x-battle'
    | '/industries'
    | '/labs'
    | '/api/x-intel/anti-echo'
    | '/api/x-intel/post-room'
    | '/api/x-intel/x-battle'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/checkout'
    | '/cleanseek'
    | '/cleanseek-x'
    | '/faq'
    | '/helper'
    | '/pricing'
    | '/pulse'
    | '/seekly'
    | '/signin'
    | '/success'
    | '/ticker'
    | '/xmarks'
    | '/api/pulse-runs'
    | '/api/pulse-voices'
    | '/api/second-opinion'
    | '/api/supplementary'
    | '/api/unusual-whales'
    | '/cleanseek-x/desktop'
    | '/cleanseek-x/history'
    | '/cleanseek-x/rabbitholex'
    | '/industries/$vertical'
    | '/labs/anti-echo'
    | '/labs/matrix'
    | '/labs/post-room'
    | '/labs/x-battle'
    | '/industries/'
    | '/labs/'
    | '/api/x-intel/anti-echo'
    | '/api/x-intel/post-room'
    | '/api/x-intel/x-battle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  CleanseekRoute: typeof CleanseekRoute
  CleanseekXRoute: typeof CleanseekXRouteWithChildren
  FaqRoute: typeof FaqRoute
  HelperRoute: typeof HelperRoute
  PricingRoute: typeof PricingRoute
  PulseRoute: typeof PulseRoute
  SeeklyRoute: typeof SeeklyRoute
  SigninRoute: typeof SigninRoute
  SuccessRoute: typeof SuccessRoute
  TickerRoute: typeof TickerRoute
  XmarksRoute: typeof XmarksRoute
  ApiPulseRunsRoute: typeof ApiPulseRunsRoute
  ApiPulseVoicesRoute: typeof ApiPulseVoicesRoute
  ApiSecondOpinionRoute: typeof ApiSecondOpinionRoute
  ApiSupplementaryRoute: typeof ApiSupplementaryRoute
  ApiUnusualWhalesRoute: typeof ApiUnusualWhalesRoute
  IndustriesVerticalRoute: typeof IndustriesVerticalRoute
  LabsAntiEchoRoute: typeof LabsAntiEchoRoute
  LabsMatrixRoute: typeof LabsMatrixRoute
  LabsPostRoomRoute: typeof LabsPostRoomRoute
  LabsXBattleRoute: typeof LabsXBattleRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  LabsIndexRoute: typeof LabsIndexRoute
  ApiXIntelAntiEchoRoute: typeof ApiXIntelAntiEchoRoute
  ApiXIntelPostRoomRoute: typeof ApiXIntelPostRoomRoute
  ApiXIntelXBattleRoute: typeof ApiXIntelXBattleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xmarks': {
      id: '/xmarks'
      path: '/xmarks'
      fullPath: '/xmarks'
      preLoaderRoute: typeof XmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker': {
      id: '/ticker'
      path: '/ticker'
      fullPath: '/ticker'
      preLoaderRoute: typeof TickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seekly': {
      id: '/seekly'
      path: '/seekly'
      fullPath: '/seekly'
      preLoaderRoute: typeof SeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper': {
      id: '/helper'
      path: '/helper'
      fullPath: '/helper'
      preLoaderRoute: typeof HelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanseek-x': {
      id: '/cleanseek-x'
      path: '/cleanseek-x'
      fullPath: '/cleanseek-x'
      preLoaderRoute: typeof CleanseekXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanseek': {
      id: '/cleanseek'
      path: '/cleanseek'
      fullPath: '/cleanseek'
      preLoaderRoute: typeof CleanseekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/x-battle': {
      id: '/labs/x-battle'
      path: '/labs/x-battle'
      fullPath: '/labs/x-battle'
      preLoaderRoute: typeof LabsXBattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/post-room': {
      id: '/labs/post-room'
      path: '/labs/post-room'
      fullPath: '/labs/post-room'
      preLoaderRoute: typeof LabsPostRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/matrix': {
      id: '/labs/matrix'
      path: '/labs/matrix'
      fullPath: '/labs/matrix'
      preLoaderRoute: typeof LabsMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/anti-echo': {
      id: '/labs/anti-echo'
      path: '/labs/anti-echo'
      fullPath: '/labs/anti-echo'
      preLoaderRoute: typeof LabsAntiEchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$vertical': {
      id: '/industries/$vertical'
      path: '/industries/$vertical'
      fullPath: '/industries/$vertical'
      preLoaderRoute: typeof IndustriesVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanseek-x/rabbitholex': {
      id: '/cleanseek-x/rabbitholex'
      path: '/rabbitholex'
      fullPath: '/cleanseek-x/rabbitholex'
      preLoaderRoute: typeof CleanseekXRabbitholexRouteImport
      parentRoute: typeof CleanseekXRoute
    }
    '/cleanseek-x/history': {
      id: '/cleanseek-x/history'
      path: '/history'
      fullPath: '/cleanseek-x/history'
      preLoaderRoute: typeof CleanseekXHistoryRouteImport
      parentRoute: typeof CleanseekXRoute
    }
    '/cleanseek-x/desktop': {
      id: '/cleanseek-x/desktop'
      path: '/desktop'
      fullPath: '/cleanseek-x/desktop'
      preLoaderRoute: typeof CleanseekXDesktopRouteImport
      parentRoute: typeof CleanseekXRoute
    }
    '/api/unusual-whales': {
      id: '/api/unusual-whales'
      path: '/api/unusual-whales'
      fullPath: '/api/unusual-whales'
      preLoaderRoute: typeof ApiUnusualWhalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supplementary': {
      id: '/api/supplementary'
      path: '/api/supplementary'
      fullPath: '/api/supplementary'
      preLoaderRoute: typeof ApiSupplementaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/second-opinion': {
      id: '/api/second-opinion'
      path: '/api/second-opinion'
      fullPath: '/api/second-opinion'
      preLoaderRoute: typeof ApiSecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse-voices': {
      id: '/api/pulse-voices'
      path: '/api/pulse-voices'
      fullPath: '/api/pulse-voices'
      preLoaderRoute: typeof ApiPulseVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulse-runs': {
      id: '/api/pulse-runs'
      path: '/api/pulse-runs'
      fullPath: '/api/pulse-runs'
      preLoaderRoute: typeof ApiPulseRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x-intel/x-battle': {
      id: '/api/x-intel/x-battle'
      path: '/api/x-intel/x-battle'
      fullPath: '/api/x-intel/x-battle'
      preLoaderRoute: typeof ApiXIntelXBattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x-intel/post-room': {
      id: '/api/x-intel/post-room'
      path: '/api/x-intel/post-room'
      fullPath: '/api/x-intel/post-room'
      preLoaderRoute: typeof ApiXIntelPostRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x-intel/anti-echo': {
      id: '/api/x-intel/anti-echo'
      path: '/api/x-intel/anti-echo'
      fullPath: '/api/x-intel/anti-echo'
      preLoaderRoute: typeof ApiXIntelAntiEchoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CleanseekXRouteChildren {
  CleanseekXDesktopRoute: typeof CleanseekXDesktopRoute
  CleanseekXHistoryRoute: typeof CleanseekXHistoryRoute
  CleanseekXRabbitholexRoute: typeof CleanseekXRabbitholexRoute
}

const CleanseekXRouteChildren: CleanseekXRouteChildren = {
  CleanseekXDesktopRoute: CleanseekXDesktopRoute,
  CleanseekXHistoryRoute: CleanseekXHistoryRoute,
  CleanseekXRabbitholexRoute: CleanseekXRabbitholexRoute,
}

const CleanseekXRouteWithChildren = CleanseekXRoute._addFileChildren(
  CleanseekXRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  CleanseekRoute: CleanseekRoute,
  CleanseekXRoute: CleanseekXRouteWithChildren,
  FaqRoute: FaqRoute,
  HelperRoute: HelperRoute,
  PricingRoute: PricingRoute,
  PulseRoute: PulseRoute,
  SeeklyRoute: SeeklyRoute,
  SigninRoute: SigninRoute,
  SuccessRoute: SuccessRoute,
  TickerRoute: TickerRoute,
  XmarksRoute: XmarksRoute,
  ApiPulseRunsRoute: ApiPulseRunsRoute,
  ApiPulseVoicesRoute: ApiPulseVoicesRoute,
  ApiSecondOpinionRoute: ApiSecondOpinionRoute,
  ApiSupplementaryRoute: ApiSupplementaryRoute,
  ApiUnusualWhalesRoute: ApiUnusualWhalesRoute,
  IndustriesVerticalRoute: IndustriesVerticalRoute,
  LabsAntiEchoRoute: LabsAntiEchoRoute,
  LabsMatrixRoute: LabsMatrixRoute,
  LabsPostRoomRoute: LabsPostRoomRoute,
  LabsXBattleRoute: LabsXBattleRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  LabsIndexRoute: LabsIndexRoute,
  ApiXIntelAntiEchoRoute: ApiXIntelAntiEchoRoute,
  ApiXIntelPostRoomRoute: ApiXIntelPostRoomRoute,
  ApiXIntelXBattleRoute: ApiXIntelXBattleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
