/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CleanseekXRouteImport } from './routes/cleanseek-x'
import { Route as CleanseekRouteImport } from './routes/cleanseek'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CleanseekXRabbitholexRouteImport } from './routes/cleanseek-x/rabbitholex'
import { Route as CleanseekXHistoryRouteImport } from './routes/cleanseek-x/history'
import { Route as CleanseekXDesktopRouteImport } from './routes/cleanseek-x/desktop'
import { Route as ApiSupplementaryRouteImport } from './routes/api/supplementary'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanseekXRoute = CleanseekXRouteImport.update({
  id: '/cleanseek-x',
  path: '/cleanseek-x',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanseekRoute = CleanseekRouteImport.update({
  id: '/cleanseek',
  path: '/cleanseek',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanseekXRabbitholexRoute = CleanseekXRabbitholexRouteImport.update({
  id: '/rabbitholex',
  path: '/rabbitholex',
  getParentRoute: () => CleanseekXRoute,
} as any)
const CleanseekXHistoryRoute = CleanseekXHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CleanseekXRoute,
} as any)
const CleanseekXDesktopRoute = CleanseekXDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => CleanseekXRoute,
} as any)
const ApiSupplementaryRoute = ApiSupplementaryRouteImport.update({
  id: '/api/supplementary',
  path: '/api/supplementary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/cleanseek': typeof CleanseekRoute
  '/cleanseek-x': typeof CleanseekXRouteWithChildren
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/success': typeof SuccessRoute
  '/api/supplementary': typeof ApiSupplementaryRoute
  '/cleanseek-x/desktop': typeof CleanseekXDesktopRoute
  '/cleanseek-x/history': typeof CleanseekXHistoryRoute
  '/cleanseek-x/rabbitholex': typeof CleanseekXRabbitholexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/cleanseek': typeof CleanseekRoute
  '/cleanseek-x': typeof CleanseekXRouteWithChildren
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/success': typeof SuccessRoute
  '/api/supplementary': typeof ApiSupplementaryRoute
  '/cleanseek-x/desktop': typeof CleanseekXDesktopRoute
  '/cleanseek-x/history': typeof CleanseekXHistoryRoute
  '/cleanseek-x/rabbitholex': typeof CleanseekXRabbitholexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/cleanseek': typeof CleanseekRoute
  '/cleanseek-x': typeof CleanseekXRouteWithChildren
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/success': typeof SuccessRoute
  '/api/supplementary': typeof ApiSupplementaryRoute
  '/cleanseek-x/desktop': typeof CleanseekXDesktopRoute
  '/cleanseek-x/history': typeof CleanseekXHistoryRoute
  '/cleanseek-x/rabbitholex': typeof CleanseekXRabbitholexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/cleanseek'
    | '/cleanseek-x'
    | '/faq'
    | '/pricing'
    | '/signin'
    | '/success'
    | '/api/supplementary'
    | '/cleanseek-x/desktop'
    | '/cleanseek-x/history'
    | '/cleanseek-x/rabbitholex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/cleanseek'
    | '/cleanseek-x'
    | '/faq'
    | '/pricing'
    | '/signin'
    | '/success'
    | '/api/supplementary'
    | '/cleanseek-x/desktop'
    | '/cleanseek-x/history'
    | '/cleanseek-x/rabbitholex'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/cleanseek'
    | '/cleanseek-x'
    | '/faq'
    | '/pricing'
    | '/signin'
    | '/success'
    | '/api/supplementary'
    | '/cleanseek-x/desktop'
    | '/cleanseek-x/history'
    | '/cleanseek-x/rabbitholex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  CleanseekRoute: typeof CleanseekRoute
  CleanseekXRoute: typeof CleanseekXRouteWithChildren
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  SigninRoute: typeof SigninRoute
  SuccessRoute: typeof SuccessRoute
  ApiSupplementaryRoute: typeof ApiSupplementaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanseek-x': {
      id: '/cleanseek-x'
      path: '/cleanseek-x'
      fullPath: '/cleanseek-x'
      preLoaderRoute: typeof CleanseekXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanseek': {
      id: '/cleanseek'
      path: '/cleanseek'
      fullPath: '/cleanseek'
      preLoaderRoute: typeof CleanseekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanseek-x/rabbitholex': {
      id: '/cleanseek-x/rabbitholex'
      path: '/rabbitholex'
      fullPath: '/cleanseek-x/rabbitholex'
      preLoaderRoute: typeof CleanseekXRabbitholexRouteImport
      parentRoute: typeof CleanseekXRoute
    }
    '/cleanseek-x/history': {
      id: '/cleanseek-x/history'
      path: '/history'
      fullPath: '/cleanseek-x/history'
      preLoaderRoute: typeof CleanseekXHistoryRouteImport
      parentRoute: typeof CleanseekXRoute
    }
    '/cleanseek-x/desktop': {
      id: '/cleanseek-x/desktop'
      path: '/desktop'
      fullPath: '/cleanseek-x/desktop'
      preLoaderRoute: typeof CleanseekXDesktopRouteImport
      parentRoute: typeof CleanseekXRoute
    }
    '/api/supplementary': {
      id: '/api/supplementary'
      path: '/api/supplementary'
      fullPath: '/api/supplementary'
      preLoaderRoute: typeof ApiSupplementaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CleanseekXRouteChildren {
  CleanseekXDesktopRoute: typeof CleanseekXDesktopRoute
  CleanseekXHistoryRoute: typeof CleanseekXHistoryRoute
  CleanseekXRabbitholexRoute: typeof CleanseekXRabbitholexRoute
}

const CleanseekXRouteChildren: CleanseekXRouteChildren = {
  CleanseekXDesktopRoute: CleanseekXDesktopRoute,
  CleanseekXHistoryRoute: CleanseekXHistoryRoute,
  CleanseekXRabbitholexRoute: CleanseekXRabbitholexRoute,
}

const CleanseekXRouteWithChildren = CleanseekXRoute._addFileChildren(
  CleanseekXRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  CleanseekRoute: CleanseekRoute,
  CleanseekXRoute: CleanseekXRouteWithChildren,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  SigninRoute: SigninRoute,
  SuccessRoute: SuccessRoute,
  ApiSupplementaryRoute: ApiSupplementaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
